app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views.home_view import *
from .views.category_view import *
from .views.product_view import *
from .views.cart_view import *
from .views.wishlist_view import *
from .views.search_view import *
from .views.account_view import *

app_name = 'app'

urlpatterns = [
    path('search/', search, name='search'),
    path('login/', login_view, name='login_view'),
    path('register/', register_view, name='register_view'),
    path('logout/', logout_view, name='logout_view'),
    path('cart/', cart_detail, name='cart_detail'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/<int:cart_item_id>/', update_cart_item, name='update_cart_item'),
    path('wishlist/', wishlist, name='wishlist'),
    path('add-to-wishlist/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:product_id>/', remove_from_wishlist, name='remove_from_wishlist'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from app.views.product_view import *
from app.views.category_view import *
from .views import *
app_name = 'products'

urlpatterns = [
    path('category-list/', category_list, name='category_list'),
    path('product-list/', product_list, name='product_list'),
    path('product-detail/<int:id>/', product_detail, name='product_detail'),
    path('category/<slug>/', category_products, name='category_products'),
    path('add/', product_upload, name='product_upload'),
]

app/models/wishlist.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

class Wishlist(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, related_name='wishlists')

    def to_dict(self):
        return {
            'id': self.id,
            'user': self.user.id,
            'products': [product.id for product in self.products.all()],
        }

    def __str__(self):
        return f'Wishlist for {self.user.username}'

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# from app.models.user import User
from slugify import slugify

class Category(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='categories/', blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', args=[self.slug])


class SubCategory(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Subcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('subcategory_detail', args=[self.category.slug, self.slug])


class Size(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Color(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=6)

    def __str__(self):
        return self.name

class Brand(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='products/', blank=True)


class Product(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available_sizes = models.ManyToManyField(Size)
    available_colors = models.ManyToManyField(Color)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', blank=True)
    is_featured = models.BooleanField(default=False)
    is_newarrival = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:product_detail', args=[self.subcategory.category.slug, self.subcategory.slug, self.slug])


#class ProductVariant(models.Model):
#    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variants')
#    size = models.ForeignKey(Size, on_delete=models.CASCADE)
#    color = models.ForeignKey(Color, on_delete=models.CASCADE)
#    image = models.ImageField(upload_to='product_variants/', blank=True)
#    price = models.DecimalField(max_digits=10, decimal_places=2)
#
#    def __str__(self):
#        return f'{self.product.name} ({self.size.name}, {self.color.name})'


class Tag(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class ProductTag(models.Model):
    id = models.BigAutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f'Tag "{self.tag.name}" on "{self.product.name}"'


class Review(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Review for {self.product.name}'

products/forms.py
from django import forms
from .models import *

class ProductForm(forms.ModelForm):

    name = forms.CharField(
        label='Product Name',
        max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter product name'}),
    )
    description = forms.CharField(
        label='Description',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
    )
    price = forms.DecimalField(
        label='Price',
        decimal_places=2,
        max_digits=10,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter price'}),
    )
    available_sizes = forms.ModelMultipleChoiceField(
        label='Available Sizes',
        queryset=Size.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
    )
    available_colors = forms.ModelMultipleChoiceField(
        label='Available Colors',
        queryset=Color.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
    )
    category = forms.ModelChoiceField(
        label='Category',
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    brand = forms.ModelChoiceField(
        label='Brand',
        queryset=Brand.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    image = forms.ImageField(
        label='Product Image',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
        required=False,
    )
    is_newarrival = forms.BooleanField(
        label='New Arrival',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'available_sizes', 'available_colors', 'category', 'brand', 'image', 'is_newarrival']

    def clean_price(self):
        price = self.cleaned_data['price']
        if price <= 0:
            raise forms.ValidationError("Price must be greater than zero.")
        return price

    def clean_image(self):
        image = self.cleaned_data['image']
        if image and image.size > 5 * 1024 * 1024: # Max file size is 5MB
            raise forms.ValidationError("Image size must be less than 5MB.")
        return image

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['price'].widget.attrs['class'] = 'form-control'
        self.fields['available_sizes'].widget.attrs['class'] = 'form-control'
        self.fields['available_colors'].widget.attrs['class'] = 'form-control'
        self.fields['category'].widget.attrs['class'] = 'form-control'
        self.fields['brand'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control-file'
        self.fields['is_newarrival'].widget.attrs['class'] = 'form-check-input'


   # def __init__(self, *args, **kwargs):
   #     super().__init__(*args, **kwargs)
   #     self.fields['available_sizes'].widget.attrs.update({'class': 'form-check-input'})
   #     self.fields['available_colors'].widget.attrs.update({'class': 'form-check-input'})
#class ProductForm(forms.ModelForm):
#    class Meta:
#        model = Product
#        fields = ['name', 'description', 'price', 'category', 'image']
#        widgets = {
#            'name': forms.TextInput(attrs={'class': 'form-control'}),
#            'description': forms.Textarea(attrs={'class': 'form-control'}),
#            'price': forms.NumberInput(attrs={'class': 'form-control'}),
#            'category': forms.Select(attrs={'class': 'form-control'}),
#            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
#        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'Category Name',
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'comment')
        widgets = {
           # 'rating': forms.Select(choices=Review.RATING_CHOICES),
            'comment': forms.Textarea(attrs={'rows': 5}),
        }

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if rating < 1 or rating > 5:
            raise forms.ValidationError('Rating must be between 1 and 5')
        return rating

app/views/category_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from products.models import Category
from products.forms import CategoryForm

@login_required
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category_list.html', {'categories': categories})

@login_required
@staff_member_required
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category created successfully')
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'category_create.html', {'form': form})

@login_required
@staff_member_required
def category_edit(request, slug):
    category = get_object_or_404(Category, slug=slug)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category updated successfully')
            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'category_edit.html', {'form': form, 'category': category})

@login_required
@staff_member_required
def category_delete(request, slug):
    category = get_object_or_404(Category, slug=slug)
    if request.method == 'POST':
        category.delete()
        messages.success(request, 'Category deleted successfully')
        return redirect('category_list')
    return render(request, 'category_delete.html', {'category': category})

app/views/product_view.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views.generic import ListView

from products.models import Product, Review, Category
# from ..models.order import Order
from products.forms import ReviewForm


def product_list(request):
    """
    View function for product list page.
    Displays all the products in the database.
    """

    # Get all the products
    products = Product.objects.all()

    context = {'products': products}

    return render(request, 'product_list.html', context)


def product_detail(request, id):
    """
    View function for product detail page.
    Displays detailed information about a specific product.
    """

    # Get the product with the given id
    product = get_object_or_404(Product, id=id)

    # Get the related products (products in the same category)
    related_products = Product.objects.filter(category=product.category).exclude(id=id)

    context = {'product': product,
               'related_products': related_products,
             }

    return render(request, 'product_detail.html', context)

class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'
    paginate_by = 12


def category_products(request, slug):
    category = Category.objects.get(slug=slug)
    products = Product.objects.filter(category=category)
    query = request.GET.get('q')
    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'category_products.html', context)

app/views/wishlist_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from ..models.wishlist import Wishlist
from products.models import Product

@login_required
def add_to_wishlist(request, product_id):
    """
    View to add a product to user's wishlist
    """
    product = Product.objects.get(id=product_id)
    wishlist_item, created = Wishlist.objects.get_or_create(user=request.user)
    wishlist_item.products.add(product)
    if created:
        message = f"{product.name} has been added to your wishlist!"
    else:
        message = f"{product.name} is already in your wishlist!"
    data = {'message': message, 'wishlist_item': wishlist_item.to_dict()}
    return JsonResponse(data)


@login_required
def wishlist(request):
    """
    View to display user's wishlist
    """
    wishlist = Wishlist.objects.get(user=request.user)
    if wishlist:
        products = wishlist.products.all()
        context = {
            'wishlist': wishlist,
            'products': products
        }
        return render(request, 'wishlist.html', context)
    return render(request, 'wishlist.html', None)



@login_required
def remove_from_wishlist(request, product_id):
    """
    View to remove a product from user's wishlist
    """
    wishlist = Wishlist.objects.get(user=request.user)
    product = Product.objects.get(id=product_id)
    message = "{} has been removed from your wishlist!".format(product.name)
    wishlist.products.remove(product)
    data = {'message': message}
    return JsonResponse(data)

products/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Product
from .forms import ProductForm


@login_required
def product_upload(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.seller = request.user
            product.save()
            form.save_m2m()
            messages.success(request, 'Product uploaded successfully!')
            return redirect('products:product_detail', id=product.id)
    else:
        form = ProductForm()
    return render(request, 'product_upload.html', {'form': form})


def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})


def product_detail(request, id):
    product = Product.objects.get(id=id)
    return render(request, 'product_detail.html', {'product': product})

products/templates/category.html
{% extends 'base.html' %}

{% block title %}
    {{ category.name }} | Fashion Marketplace
{% endblock %}

{% block category_active %}
    active
{% endblock %}

{% block content %}
    <h1>{{ category.name }}</h1>

    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card h-100">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">{{ product.price }}</small>
                    <a href="{% url 'products:product' product.slug %}" class="btn btn-primary">View Product</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <p>No products found in this category.</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

products/templates/category_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Categories</h1>
  <a href="% url 'category_create' %}" class="btn btn-primary mb-3">Create New Category</a>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <td>{{ category.name }}</td>
          <td>{{ category.description }}</td>
          <td>
            <a href="% url 'category_edit' category.id %}" class="btn btn-sm btn-warning">Edit</a>
            <a href="% url 'category_delete' category.id %}" class="btn btn-sm btn-danger">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No categories found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

products/templates/category_products.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ category.name }}</h1>
<form class="form-inline mb-3">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<div class="row">
    {% for product in products %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
            <div class="card-body">
                <button class="wishlist-btn" data-product-id="123" data-action="add">
                    <i class="fa fa-heart-o"></i><span>Add to Wishlist</span>
                </button>

                <h4 class="card-title">{{ product.name }}</h4>
                <p class="card-text">{{ product.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'products:product_detail' product.id %}" class="btn btn-sm btn-outline-secondary">View</a>
                        {% if user.is_authenticated and product in user.wishlist.all %}
                        <a href="{% url 'app:remove_from_wishlist' product.id %}" class="btn btn-sm btn-outline-danger">Remove from Wishlist</a>
                        {% else %}
                        <button class="btn btn-sm btn-outline-primary wishlist-btn" data-product-id="{{ product.id }}" data-action="add">
                            <span>Add to Wishlist</span>
                        </button>
                        {% endif %}
                    </div>
                    <small class="text-muted">${{ product.price }}</small>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-md-12">
        <p>No products found.</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

products/templates/product.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <p class="text-muted">{{ product.get_category_display }}</p>
            <p class="h3">${{ product.price }}</p>
            <form method="POST" action="{% url 'app:add_to_cart' product_id=product.id %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="size" class="form-label">Size</label>
                    <select id="size" class="form-select" name="size">
                        {% for size in product.available_sizes %}
                        <option value="{{ size }}">{{ size }}</option>
                        {% endfor %}
                    </select>
                    <label for="brand" class="form-label">Brand</label>
                    <select id="brand" class="form-select" name="brand">
                        {% for brand in product.brand %}
                        <option value="{{ brand }}">{{ brand }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="quantity" class="form-label">Quantity</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" min="1" value="1" required>
                </div>
                <button type="submit" class="btn btn-primary">Add to Cart</button>
            </form>
        </div>
    </div>
    <hr>
    <h2>Description</h2>
    <p>{{ product.description }}</p>
    <hr>
    <h2>Reviews</h2>
    {% if reviews %}
    {% for review in reviews %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ review.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ review.user.username }}</h6>
            <p class="card-text">{{ review.content }}</p>
            <p class="card-text">
            <small class="text-muted">{{ review.created_at }}</small>
            </p>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No reviews yet.</p>
    {% endif %}
    {% if user.is_authenticated %}
    <hr>
    <h2>Add a Review</h2>
    <form method="POST" action="{% url 'app:add_review' product.id %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>
{% endblock %}

products/templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row position-relative">
        <div class="col-md-6 position-relative">
            <img class="img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
            <form method="POST" action="{% url 'app:add_to_wishlist' product.id %}" class="position-absolute top-0 end-0">
                {% csrf_token %}
                <button type="submit" class="heart-btn"><i class="bi bi-heart"></i></button>
            </form>
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <p>{{ product.description }}</p>
            <p>Price: ${{ product.price }}</p>
            <p>Brand: {{ product.brand.name }}</p>

            <h3>Available Sizes:</h3>
            <ul>
                {% for size in product.available_sizes.all %}
                <li>{{ size.name }}</li>
                {% endfor %}
            </ul>

            <h3>Available Colors:</h3>
            <ul>
                {% for color in product.available_colors.all %}
                <li>{{ color.name }}</li>
                {% endfor %}
            </ul>
            <form method="POST" action="{% url 'app:add_to_cart' product.id %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="quantity" class="form-label">Quantity</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" min="1" value="1" required>
                </div>
                <button type="submit" class="btn btn-primary">Add to Cart</button>
            </form>

        </div>
    </div>

    <hr>
    <h2>Description</h2>
    <p>{{ product.description }}</p>
    <hr>
    <h2>Reviews</h2>
    {% if reviews %}
    {% for review in reviews %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ review.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ review.user.username }}</h6>
            <p class="card-text">{{ review.content }}</p>
            <p class="card-text">
            <small class="text-muted">{{ review.created_at }}</small>
            </p>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No reviews yet.</p>
    {% endif %}
    {% if user.is_authenticated %}
    <hr>
    <h2>Add a Review</h2>
    <form method="POST" action="% url 'add_review' product.id %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>
{% endblock %}

products/templates/product_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Products</h1>
<div class="row">
    {% for product in products %}

    <div class="col-md-3">
        <div class="card mb-3 box-shadow">
            <div class="badge">Hot</div>
            <div class="product-tumb">
                <img src="{{ product.image.url }}" alt="">
            </div>
            <div class="product-details">
                <span class="product-catagory">{{ product.category }}</span>
                <h4><a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a></h4>
                <p>{{ product.description }}</p>
                <div class="product-bottom-details">
                    <div class="product-price">{{ product.price }} <small>Birr</small></div>
                    <div class="product-links">
                        <button class="wishlist-btn {% if product in user.wishlist.products.all %}added{% endif %}"
                                data-product-id="{{ product.id }}"
                                data-action="{% if product in user.wishlist.products.all %}remove{% else %}add{% endif %}">
                            <i class="fa {% if product in user.wishlist.products.all %}fa-heart{% else %}fa-heart-o{% endif %}"></i>
                        </button>
                        {% csrf_token %}
                        <button class="cart-btn {% if product in user.wishlist.products.all %}added{% endif %}"
                                data-product-id="{{ product.id }}"
                                data-action="{% if product in user.wishlist.products.all %}remove{% else %}add{% endif %}">
                            <i class="{% if product in user.wishlist.products.all %}fa fa-shopping-cart{% else %}far fa-shopping-cart{% endif %}"></i>
                        </button>

                        <!-- <button class="wishlist-btn" data-product-id="{{ product.id }}" data-action="add"></button>
                            <a href=""><i class="fa fa-shopping-cart"></i></a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="card mb-4 shadow-sm">
        <div class="heart-button-container">
        <button class="heart-button {% if product.id in wishlist %}active{% endif %}" data-product-id="{{ product.id }}"><i class="fa fa-heart"></i></button>
        </div>
        <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
        <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text"><strong>Price:</strong> ${{ product.price }}</p>
        <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary">View Product</a>
        </div>
        </div> -->
        {% empty %}
        <p>There are no products available.</p>
        {% endfor %}
</div>
{% endblock %}